baseURL = "https://docomola.github.io/myblog/"
title = "My Blog"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

# disableKinds = ["taxonomy"]

[outputs]
home = ["HTML", "RSS", "JSON"]
