# use the setting below to set multiple docs directories.
# docSections = ["docs", "tutorials"]

uniqueHomePage = true # change to false to add sidebar to homepage

blogDir = "posts" # can be posts, blog etc.

repo = "https://github.com/docomola/myblog"

time_format_blog = "2006年01月02日"
time_format_default = "2006年01月02日"
enableDarkMode = true                         # 允许用户切换深色模式
defaultLightingMode = "auto"                 # 跟随系统

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 15

# show/hide line numbers by default. Switch to `true` if you'd rather have them on.
showLineNumbers = false

otherSearchableFields = [
  "Tags",
  "Categories",
] # As they appear in frontmatter

# Defaults to true if not set
# Enable copyRight Footer Stamp. Takes in attribution
enableCopyright = false

# search
[search]
on = true
global = false # turn to `true` to enable global search
[search.algolia]
enable = false                           # if false search will default to fusejs
id = ""
index = ""
key = ""

# Site logo
[logo]
lightMode = "/images/compose.svg"
darkMode = "/images/compose-light.svg"

[source]
name = "GitHub"
iconLight = "/images/GitHubMarkLight.svg"
iconDark = "/images/GitHubMarkDark.svg"
url = "https://github.com/docomola/myblog"

# optional
# attribution. Feel free to delete this
[author]
name = "docomola"
url = "https://docomola.github.io/myblog/"
